name: Pre-submit Fluentbit Image Builder

on:
  pull_request_target:
    types: [opened, synchronize]

env:
  BUILD_MODE: release

jobs:
  envs:
    runs-on: ubuntu-latest
    outputs:
      build-args: ${{ steps.prepare-envs.outputs.build-args }}
      flb-version: ${{ steps.load-envs.outputs.FLB_VERSION }}
      semver: ${{ steps.prepare-envs.outputs.semver }}

    steps:
      - name: Echo current github workspace
        run: echo $GITHUB_WORKSPACE

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Echo github workspace after checkout
        run: echo $GITHUB_WORKSPACE

      - name: Prepare Envs
        id: prepare-envs
        run: |
          {
          # this creates a multiline string with the envs. 
          # Everything between `build-args<<BUILD_ARGS` and BUILD_ARGS will be content of the build-args variable.
          echo 'build-args<<BUILD_ARGS'
          echo "BUILD_MODE=${{ env.BUILD_MODE }}"
          cat fluent-bit/envs
          echo BUILD_ARGS

          } >> "$GITHUB_OUTPUT"

      - name: load envs into output
        id: load-envs
        run: |
          cat fluent-bit/envs >> "$GITHUB_OUTPUT"
